version: '3'

services:
  app:
    build: .
    image: taxeer_app:1.2.1
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      - BOT_API_KEY=${BOT_API}
      - DB_HOST_KEY=db
      - DB_USER_KEY=taxeer
      - DB_PASSWORD_KEY=${DB_PASSWORD}
      - DB_NAME_KEY=taxeer
    restart: unless-stopped

  db:
    image: "postgres:13-alpine"
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=taxeer
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=taxeer
    restart: unless-stopped

volumes:
  db_data:
