version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      - BOT_API_KEY=${BOT_API}
      - DB_HOST_KEY=db
      - DB_USER_KEY=${DB_USER}
      - DB_PASSWORD_KEY=${DB_PASSWORD}
      - DB_NAME_KEY=${DB_NAME}
    restart: on-failure

  db:
    image: "postgres:13-alpine"
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
