// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type TaxeerRecord struct {
	ID             uuid.UUID
	TaxeerUserID   uuid.UUID
	Date           time.Time
	IncomeValue    float64
	IncomeCurrency string
	Rate           float64
}

type TaxeerUser struct {
	ID             uuid.UUID
	TelegramUserID string
	ChatID         int64
}
